version: '3.8'

networks:
  influx-grafana:
    name: influx-grafana
    driver: bridge

services:
  influxdb:
    image: influxdb:2.4
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=influx-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=influx-pass
      - DOCKER_INFLUXDB_INIT_ORG=influx-org
      - DOCKER_INFLUXDB_INIT_BUCKET=influx-bu
    ports:
      - 8086:8086
    volumes:
      - ./influx-data:/var/lib/influxdb
    networks:
      - influx-grafana

  grafana:
    image: grafana/grafana:9.2.1
    ports:
      - 3000:3000
    networks:
      - influx-grafana

